name: SMEPro Orchestrator - Deploy to Production

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'infrastructure/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'prod'
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  AZURE_CONTAINER_REGISTRY: crsmeproprod.azurecr.io
  IMAGE_NAME: smepro-orchestrator
  KUBERNETES_NAMESPACE: smepro

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8 black

      - name: Lint with flake8
        run: |
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Format check with black
        run: |
          black --check src

      - name: Run tests
        run: |
          pytest tests/ --cov=src --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml

  build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            VCS_REF=${{ github.sha }}

  deploy-infrastructure:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"
          terraform_wrapper: false

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        working-directory: ./infrastructure/terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./infrastructure/terraform
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ./infrastructure/terraform
        run: terraform apply -auto-approve tfplan

      - name: Export Terraform Outputs
        working-directory: ./infrastructure/terraform
        run: terraform output -json > ../../config/terraform-outputs.json

  deploy-kubernetes:
    needs: deploy-infrastructure
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubectl
        run: |
          az aks get-credentials \
            --name aks-smepro-prod \
            --resource-group rg-smepro-prod \
            --overwrite-existing

      - name: Update Kubernetes manifests
        run: |
          sed -i 's|image: crsmeproprod.azurecr.io/smepro-orchestrator:.*|image: crsmeproprod.azurecr.io/smepro-orchestrator:${{ github.sha }}|' \
            infrastructure/kubernetes/orchestrator-deployment.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f infrastructure/kubernetes/namespace.yaml
          kubectl apply -f infrastructure/kubernetes/orchestrator-deployment.yaml
          kubectl apply -f infrastructure/kubernetes/ingress.yaml

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/smepro-orchestrator \
            -n ${{ env.KUBERNETES_NAMESPACE }} \
            --timeout=300s

      - name: Verify deployment
        run: |
          kubectl get pods -n ${{ env.KUBERNETES_NAMESPACE }}
          kubectl get svc -n ${{ env.KUBERNETES_NAMESPACE }}

  smoke-tests:
    needs: deploy-kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubectl
        run: |
          az aks get-credentials \
            --name aks-smepro-prod \
            --resource-group rg-smepro-prod

      - name: Run smoke tests
        run: |
          kubectl port-forward svc/smepro-orchestrator 8080:80 -n smepro &
          sleep 5
          
          # Health check
          curl -f http://localhost:8080/health || exit 1
          
          # API readiness
          curl -f http://localhost:8080/ready || exit 1
          
          # Test report generation endpoint
          curl -X POST http://localhost:8080/api/v1/reports/generate \
            -H "Content-Type: application/json" \
            -d '{"prompt":"test","course_context":{"cip_code":"52.0201"}}' \
            || exit 1
          
          echo "Smoke tests passed!"

  notify:
    needs: [smoke-tests]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify Slack - Success
        if: needs.smoke-tests.result == 'success'
        uses: 8398a7/action-slack@v3
        with:
          status: success
          channel: '#smepro-deployments'
          text: |
            ✅ SMEPro Orchestrator deployed successfully!
            
            Environment: Production
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
            
            API: https://api.smepro.lamar.edu
            Apps: https://apps.smepro.lamar.edu
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack - Failure
        if: needs.smoke-tests.result == 'failure'
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          channel: '#smepro-deployments'
          text: |
            ❌ SMEPro Orchestrator deployment failed!
            
            Environment: Production
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
            
            Check logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
